name: unit test check

on:
  push:
    branches: 
      - main
      - release/**
  pull_request:
    branches: 
      - main
      - release/**

jobs:
  unit_test:
    name: Run unit test
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - run: bash run_test.sh